// Data on continents and countries to be sorted and rendered

const data = [
  {
    id: 1,
    continent: 'Africa',
    country: [
      'Algeria',
      'Angola',
      'Benin',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cape Verde',
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Comoros',
      'Congo (Brazzaville)',
      'Congo (Kinshasa)',
      'Cote d\'Ivoire',
      'Djibouti',
      'Egypt',
      'Equatorial Guinea',
      'Eritrea',
      'Eswatini',
      'Ethiopia',
      'Gabon',
      'Gambia',
      'Ghana',
      'Guinea',
      'Guinea-Bissau',
      'Kenya',
      'Lesotho',
      'Liberia',
      'Libya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Mauritania',
      'Mauritius',
      'Morocco',
      'Mozambique',
      'Namibia',
      'Niger',
      'Nigeria',
      'Rwanda',
      'Sao Tome and Principe',
      'Senegal',
      'Seychelles',
      'Sierra Leone',
      'Somalia',
      'South Africa',
      'South Sudan',
      'Sudan',
      'Tanzania',
      'Togo',
      'Tunisia',
      'Uganda',
      'Western Sahara',
      'Zambia',
      'Zimbabwe',
    ],
    picked: false,
  },
  {
    id: 2,
    continent: 'Asia',
    country: ['Afghanistan',
      'Armenia',
      'Azerbaijan',
      'Bahrain',
      'Bangladesh',
      'Bhutan',
      'Brunei',
      'Burma',
      'Cambodia',
      'China',
      'Cyprus',
      'Georgia',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Kuwait',
      'Kyrgyzstan',
      'Laos',
      'Lebanon',
      'Malaysia',
      'Maldives',
      'Mongolia',
      'Nepal',
      'Oman',
      'Pakistan',
      'Philippines',
      'Qatar',
      'Russia',
      'Saudi Arabia',
      'Singapore',
      'Sri Lanka',
      'Syria',
      'Taiwan',
      'Tajikistan',
    ],
    picked: false,
  },
  {
    id: 3,
    continent: 'Europe',
    country: ['Albania',
      'Andorra',
      'Armenia',
      'Austria',
      'Azerbaijan',
      'Belarus',
      'Belgium',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Croatia',
      'Cyprus',
      'Czechia/Czech Republic',
      'Denmark',
      'Estonia',
      'Finland',
      'France',
      'Georgia',
      'Germany',
      'Greece',
      'Guernsey',
      'Holy See',
      'Hungary',
      'Iceland',
      'Ireland',
      'Italy',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Moldova',
      'Monaco',
      'Montenegro',
      'Netherlands',
      'North Macedonia',
      'Norway',
      'Poland',
      'Portugal',
      'Romania',
      'Russia',
      'San Marino',
      'Serbia',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Sweden',
      'Switzerland',
      'Turkey',
      'Ukraine',
      'United Kingdom'],
    picked: false,
  },
  {
    id: 4,
    continent: 'North America',
    country: ['Antigua and Barbuda',
      'Bahamas',
      'Barbados',
      'Belize',
      'Canada',
      'Costa Rica',
      'Cuba',
      'Dominica',
      'Dominican Republic',
      'El Salvador',
      'Grenada',
      'Guatemala',
      'Haiti',
      'Honduras',
      'Jamaica',
      'Mexico',
      'Nicaragua',
      'Panama',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'US'],
    picked: false,
  },
  {
    id: 5,
    continent: 'Oceania',
    country: ['Australia',
      'Fiji',
      'Micronesia',
      'New Zealand',
      'Papua New Guinea',
      'Samoa',
      'Vanuatu'],
    picked: false,
  },
  {
    id: 6,
    continent: 'South America',
    country: ['Argentina',
      'Bolivia',
      'Brazil',
      'Chile',
      'Colombia',
      'Ecuador',
      'Guyana',
      'Paraguay',
      'Peru',
      'Suriname',
      'Trinidad and Tobago',
      'Uruguay',
      'Venezuela'],
    picked: true,
  },
];

export default data;
